// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tgw_adm.proto

/*
Package tgwadm is a generated protocol buffer package.

It is generated from these files:
	tgw_adm.proto

It has these top-level messages:
	CtrlMsg
	ReqTgwadmSetServiceList
	RspTgwadmSetServiceList
	ReqTgwadmDelServiceList
	RspTgwadmDelServiceList
	ReqTgwadmSetConf
	RspTgwadmSetConf
	ReqTgwadmVipSegmentList
	RspTgwadmVipSegmentList
*/
package tgwadm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/Miss-you/go-presscall/pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 命令类型
type CmdType int32

const (
	CmdType_REQ_TGWADM_SET_CONF         CmdType = 20000
	CmdType_RSP_TGWADM_SET_CONF         CmdType = 20001
	CmdType_REQ_TGWADM_VIP_SEGMENT_LIST CmdType = 20002
	CmdType_RSP_TGWADM_VIP_SEGMENT_LIST CmdType = 20003
	CmdType_REQ_TGWADM_SET_SERVICE_LIST CmdType = 20004
	CmdType_RSP_TGWADM_SET_SERVICE_LIST CmdType = 20005
	CmdType_REQ_TGWADM_DEL_SERVICE_LIST CmdType = 20006
	CmdType_RSP_TGWADM_DEL_SERVICE_LIST CmdType = 20007
)

var CmdType_name = map[int32]string{
	20000: "REQ_TGWADM_SET_CONF",
	20001: "RSP_TGWADM_SET_CONF",
	20002: "REQ_TGWADM_VIP_SEGMENT_LIST",
	20003: "RSP_TGWADM_VIP_SEGMENT_LIST",
	20004: "REQ_TGWADM_SET_SERVICE_LIST",
	20005: "RSP_TGWADM_SET_SERVICE_LIST",
	20006: "REQ_TGWADM_DEL_SERVICE_LIST",
	20007: "RSP_TGWADM_DEL_SERVICE_LIST",
}
var CmdType_value = map[string]int32{
	"REQ_TGWADM_SET_CONF":         20000,
	"RSP_TGWADM_SET_CONF":         20001,
	"REQ_TGWADM_VIP_SEGMENT_LIST": 20002,
	"RSP_TGWADM_VIP_SEGMENT_LIST": 20003,
	"REQ_TGWADM_SET_SERVICE_LIST": 20004,
	"RSP_TGWADM_SET_SERVICE_LIST": 20005,
	"REQ_TGWADM_DEL_SERVICE_LIST": 20006,
	"RSP_TGWADM_DEL_SERVICE_LIST": 20007,
}

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}
func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}
func (x *CmdType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CmdType_value, data, "CmdType")
	if err != nil {
		return err
	}
	*x = CmdType(value)
	return nil
}
func (CmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 消息
type CtrlMsg struct {
	Header                  *common.Head             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	ReqTgwadmSetConf        *ReqTgwadmSetConf        `protobuf:"bytes,2,opt,name=req_tgwadm_set_conf,json=reqTgwadmSetConf" json:"req_tgwadm_set_conf,omitempty"`
	RspTgwadmSetConf        *RspTgwadmSetConf        `protobuf:"bytes,3,opt,name=rsp_tgwadm_set_conf,json=rspTgwadmSetConf" json:"rsp_tgwadm_set_conf,omitempty"`
	ReqTgwadmVipSegmentList *ReqTgwadmVipSegmentList `protobuf:"bytes,4,opt,name=req_tgwadm_vip_segment_list,json=reqTgwadmVipSegmentList" json:"req_tgwadm_vip_segment_list,omitempty"`
	RspTgwadmVipSegmentList *RspTgwadmVipSegmentList `protobuf:"bytes,5,opt,name=rsp_tgwadm_vip_segment_list,json=rspTgwadmVipSegmentList" json:"rsp_tgwadm_vip_segment_list,omitempty"`
	ReqTgwadmSetServiceList *ReqTgwadmSetServiceList `protobuf:"bytes,6,opt,name=req_tgwadm_set_service_list,json=reqTgwadmSetServiceList" json:"req_tgwadm_set_service_list,omitempty"`
	RspTgwadmSetServiceList *RspTgwadmSetServiceList `protobuf:"bytes,7,opt,name=rsp_tgwadm_set_service_list,json=rspTgwadmSetServiceList" json:"rsp_tgwadm_set_service_list,omitempty"`
	ReqTgwadmDelServiceList *ReqTgwadmDelServiceList `protobuf:"bytes,8,opt,name=req_tgwadm_del_service_list,json=reqTgwadmDelServiceList" json:"req_tgwadm_del_service_list,omitempty"`
	RspTgwadmDelServiceList *RspTgwadmDelServiceList `protobuf:"bytes,9,opt,name=rsp_tgwadm_del_service_list,json=rspTgwadmDelServiceList" json:"rsp_tgwadm_del_service_list,omitempty"`
	XXX_unrecognized        []byte                   `json:"-"`
}

func (m *CtrlMsg) Reset()                    { *m = CtrlMsg{} }
func (m *CtrlMsg) String() string            { return proto.CompactTextString(m) }
func (*CtrlMsg) ProtoMessage()               {}
func (*CtrlMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CtrlMsg) GetHeader() *common.Head {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CtrlMsg) GetReqTgwadmSetConf() *ReqTgwadmSetConf {
	if m != nil {
		return m.ReqTgwadmSetConf
	}
	return nil
}

func (m *CtrlMsg) GetRspTgwadmSetConf() *RspTgwadmSetConf {
	if m != nil {
		return m.RspTgwadmSetConf
	}
	return nil
}

func (m *CtrlMsg) GetReqTgwadmVipSegmentList() *ReqTgwadmVipSegmentList {
	if m != nil {
		return m.ReqTgwadmVipSegmentList
	}
	return nil
}

func (m *CtrlMsg) GetRspTgwadmVipSegmentList() *RspTgwadmVipSegmentList {
	if m != nil {
		return m.RspTgwadmVipSegmentList
	}
	return nil
}

func (m *CtrlMsg) GetReqTgwadmSetServiceList() *ReqTgwadmSetServiceList {
	if m != nil {
		return m.ReqTgwadmSetServiceList
	}
	return nil
}

func (m *CtrlMsg) GetRspTgwadmSetServiceList() *RspTgwadmSetServiceList {
	if m != nil {
		return m.RspTgwadmSetServiceList
	}
	return nil
}

func (m *CtrlMsg) GetReqTgwadmDelServiceList() *ReqTgwadmDelServiceList {
	if m != nil {
		return m.ReqTgwadmDelServiceList
	}
	return nil
}

func (m *CtrlMsg) GetRspTgwadmDelServiceList() *RspTgwadmDelServiceList {
	if m != nil {
		return m.RspTgwadmDelServiceList
	}
	return nil
}

type ReqTgwadmSetServiceList struct {
	Svc              []*common.Service `protobuf:"bytes,1,rep,name=svc" json:"svc,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ReqTgwadmSetServiceList) Reset()                    { *m = ReqTgwadmSetServiceList{} }
func (m *ReqTgwadmSetServiceList) String() string            { return proto.CompactTextString(m) }
func (*ReqTgwadmSetServiceList) ProtoMessage()               {}
func (*ReqTgwadmSetServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqTgwadmSetServiceList) GetSvc() []*common.Service {
	if m != nil {
		return m.Svc
	}
	return nil
}

type RspTgwadmSetServiceList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RspTgwadmSetServiceList) Reset()                    { *m = RspTgwadmSetServiceList{} }
func (m *RspTgwadmSetServiceList) String() string            { return proto.CompactTextString(m) }
func (*RspTgwadmSetServiceList) ProtoMessage()               {}
func (*RspTgwadmSetServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReqTgwadmDelServiceList struct {
	Svc              []*common.ServiceID `protobuf:"bytes,1,rep,name=svc" json:"svc,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ReqTgwadmDelServiceList) Reset()                    { *m = ReqTgwadmDelServiceList{} }
func (m *ReqTgwadmDelServiceList) String() string            { return proto.CompactTextString(m) }
func (*ReqTgwadmDelServiceList) ProtoMessage()               {}
func (*ReqTgwadmDelServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqTgwadmDelServiceList) GetSvc() []*common.ServiceID {
	if m != nil {
		return m.Svc
	}
	return nil
}

type RspTgwadmDelServiceList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RspTgwadmDelServiceList) Reset()                    { *m = RspTgwadmDelServiceList{} }
func (m *RspTgwadmDelServiceList) String() string            { return proto.CompactTextString(m) }
func (*RspTgwadmDelServiceList) ProtoMessage()               {}
func (*RspTgwadmDelServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReqTgwadmSetConf struct {
	Status             *uint32              `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Tcpactivetimeout   *uint32              `protobuf:"varint,2,opt,name=tcpactivetimeout" json:"tcpactivetimeout,omitempty"`
	Tcpinactivetimeout *uint32              `protobuf:"varint,3,opt,name=tcpinactivetimeout" json:"tcpinactivetimeout,omitempty"`
	Udptimeout         *uint32              `protobuf:"varint,4,opt,name=udptimeout" json:"udptimeout,omitempty"`
	Syncmasteractive   *uint32              `protobuf:"varint,5,opt,name=syncmasteractive" json:"syncmasteractive,omitempty"`
	Syncmasterid       *uint32              `protobuf:"varint,6,opt,name=syncmasterid" json:"syncmasterid,omitempty"`
	Syncmasterifn      *string              `protobuf:"bytes,7,opt,name=syncmasterifn" json:"syncmasterifn,omitempty"`
	Syncbackupactive   *uint32              `protobuf:"varint,8,opt,name=syncbackupactive" json:"syncbackupactive,omitempty"`
	Syncbackupid       *uint32              `protobuf:"varint,9,opt,name=syncbackupid" json:"syncbackupid,omitempty"`
	Syncbackupifn      *string              `protobuf:"bytes,10,opt,name=syncbackupifn" json:"syncbackupifn,omitempty"`
	Ldtype             *uint32              `protobuf:"varint,11,opt,name=ldtype" json:"ldtype,omitempty"`
	Ldip               []uint32             `protobuf:"varint,12,rep,name=ldip" json:"ldip,omitempty"`
	Vipsegment         []*common.VipSegment `protobuf:"bytes,13,rep,name=vipsegment" json:"vipsegment,omitempty"`
	XXX_unrecognized   []byte               `json:"-"`
}

func (m *ReqTgwadmSetConf) Reset()                    { *m = ReqTgwadmSetConf{} }
func (m *ReqTgwadmSetConf) String() string            { return proto.CompactTextString(m) }
func (*ReqTgwadmSetConf) ProtoMessage()               {}
func (*ReqTgwadmSetConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReqTgwadmSetConf) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetTcpactivetimeout() uint32 {
	if m != nil && m.Tcpactivetimeout != nil {
		return *m.Tcpactivetimeout
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetTcpinactivetimeout() uint32 {
	if m != nil && m.Tcpinactivetimeout != nil {
		return *m.Tcpinactivetimeout
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetUdptimeout() uint32 {
	if m != nil && m.Udptimeout != nil {
		return *m.Udptimeout
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetSyncmasteractive() uint32 {
	if m != nil && m.Syncmasteractive != nil {
		return *m.Syncmasteractive
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetSyncmasterid() uint32 {
	if m != nil && m.Syncmasterid != nil {
		return *m.Syncmasterid
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetSyncmasterifn() string {
	if m != nil && m.Syncmasterifn != nil {
		return *m.Syncmasterifn
	}
	return ""
}

func (m *ReqTgwadmSetConf) GetSyncbackupactive() uint32 {
	if m != nil && m.Syncbackupactive != nil {
		return *m.Syncbackupactive
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetSyncbackupid() uint32 {
	if m != nil && m.Syncbackupid != nil {
		return *m.Syncbackupid
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetSyncbackupifn() string {
	if m != nil && m.Syncbackupifn != nil {
		return *m.Syncbackupifn
	}
	return ""
}

func (m *ReqTgwadmSetConf) GetLdtype() uint32 {
	if m != nil && m.Ldtype != nil {
		return *m.Ldtype
	}
	return 0
}

func (m *ReqTgwadmSetConf) GetLdip() []uint32 {
	if m != nil {
		return m.Ldip
	}
	return nil
}

func (m *ReqTgwadmSetConf) GetVipsegment() []*common.VipSegment {
	if m != nil {
		return m.Vipsegment
	}
	return nil
}

type RspTgwadmSetConf struct {
	RetMsg           *common.RetMsg `protobuf:"bytes,1,opt,name=ret_msg,json=retMsg" json:"ret_msg,omitempty"`
	Version          *string        `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RspTgwadmSetConf) Reset()                    { *m = RspTgwadmSetConf{} }
func (m *RspTgwadmSetConf) String() string            { return proto.CompactTextString(m) }
func (*RspTgwadmSetConf) ProtoMessage()               {}
func (*RspTgwadmSetConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RspTgwadmSetConf) GetRetMsg() *common.RetMsg {
	if m != nil {
		return m.RetMsg
	}
	return nil
}

func (m *RspTgwadmSetConf) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type ReqTgwadmVipSegmentList struct {
	Type             *common.SegmentOpType `protobuf:"varint,1,opt,name=type,enum=common.SegmentOpType" json:"type,omitempty"`
	Vipsegment       []*common.VipSegment  `protobuf:"bytes,2,rep,name=vipsegment" json:"vipsegment,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ReqTgwadmVipSegmentList) Reset()                    { *m = ReqTgwadmVipSegmentList{} }
func (m *ReqTgwadmVipSegmentList) String() string            { return proto.CompactTextString(m) }
func (*ReqTgwadmVipSegmentList) ProtoMessage()               {}
func (*ReqTgwadmVipSegmentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReqTgwadmVipSegmentList) GetType() common.SegmentOpType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return common.SegmentOpType_SET
}

func (m *ReqTgwadmVipSegmentList) GetVipsegment() []*common.VipSegment {
	if m != nil {
		return m.Vipsegment
	}
	return nil
}

type RspTgwadmVipSegmentList struct {
	RetMsg           *common.RetMsg        `protobuf:"bytes,1,opt,name=ret_msg,json=retMsg" json:"ret_msg,omitempty"`
	Vipsegment       []*common.VipSegment  `protobuf:"bytes,2,rep,name=vipsegment" json:"vipsegment,omitempty"`
	Type             *common.SegmentOpType `protobuf:"varint,3,opt,name=type,enum=common.SegmentOpType" json:"type,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *RspTgwadmVipSegmentList) Reset()                    { *m = RspTgwadmVipSegmentList{} }
func (m *RspTgwadmVipSegmentList) String() string            { return proto.CompactTextString(m) }
func (*RspTgwadmVipSegmentList) ProtoMessage()               {}
func (*RspTgwadmVipSegmentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RspTgwadmVipSegmentList) GetRetMsg() *common.RetMsg {
	if m != nil {
		return m.RetMsg
	}
	return nil
}

func (m *RspTgwadmVipSegmentList) GetVipsegment() []*common.VipSegment {
	if m != nil {
		return m.Vipsegment
	}
	return nil
}

func (m *RspTgwadmVipSegmentList) GetType() common.SegmentOpType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return common.SegmentOpType_SET
}

func init() {
	proto.RegisterType((*CtrlMsg)(nil), "tgwadm.CtrlMsg")
	proto.RegisterType((*ReqTgwadmSetServiceList)(nil), "tgwadm.ReqTgwadmSetServiceList")
	proto.RegisterType((*RspTgwadmSetServiceList)(nil), "tgwadm.RspTgwadmSetServiceList")
	proto.RegisterType((*ReqTgwadmDelServiceList)(nil), "tgwadm.ReqTgwadmDelServiceList")
	proto.RegisterType((*RspTgwadmDelServiceList)(nil), "tgwadm.RspTgwadmDelServiceList")
	proto.RegisterType((*ReqTgwadmSetConf)(nil), "tgwadm.ReqTgwadmSetConf")
	proto.RegisterType((*RspTgwadmSetConf)(nil), "tgwadm.RspTgwadmSetConf")
	proto.RegisterType((*ReqTgwadmVipSegmentList)(nil), "tgwadm.ReqTgwadmVipSegmentList")
	proto.RegisterType((*RspTgwadmVipSegmentList)(nil), "tgwadm.RspTgwadmVipSegmentList")
	proto.RegisterEnum("tgwadm.CmdType", CmdType_name, CmdType_value)
}

func init() { proto.RegisterFile("tgw_adm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6f, 0xda, 0x4a,
	0x14, 0xc5, 0x65, 0x20, 0xf0, 0x72, 0xc1, 0x79, 0xbc, 0x89, 0xde, 0x8b, 0xf3, 0x22, 0xb5, 0x84,
	0x46, 0x2a, 0xcd, 0x82, 0x05, 0xeb, 0xaa, 0x52, 0x05, 0x6e, 0x8a, 0x14, 0x92, 0x74, 0x4c, 0xd3,
	0x55, 0x65, 0xb9, 0xf6, 0x40, 0xad, 0xe2, 0x3f, 0xf1, 0x0c, 0xa4, 0xf9, 0x18, 0xdd, 0x67, 0xd1,
	0xf4, 0xef, 0xf7, 0xeb, 0xb6, 0x9b, 0xca, 0x63, 0x3b, 0xd8, 0x33, 0xa0, 0x46, 0x5d, 0xc1, 0x9c,
	0x7b, 0xfc, 0xbb, 0x67, 0xc6, 0xd7, 0x03, 0x2a, 0x9b, 0x5e, 0x9a, 0x96, 0xe3, 0x75, 0xc3, 0x28,
	0x60, 0x01, 0xaa, 0xb2, 0xe9, 0xa5, 0xe5, 0x78, 0xff, 0x37, 0xec, 0xc0, 0xf3, 0x02, 0x3f, 0x51,
	0xdb, 0x3f, 0x37, 0xa0, 0xd6, 0x67, 0xd1, 0x6c, 0x44, 0xa7, 0xe8, 0x00, 0xaa, 0x6f, 0x89, 0xe5,
	0x90, 0x48, 0x53, 0x5a, 0xa5, 0x4e, 0xbd, 0xd7, 0xe8, 0xa6, 0xd6, 0xe7, 0xc4, 0x72, 0x70, 0x5a,
	0x43, 0x47, 0xb0, 0x1d, 0x91, 0x0b, 0x33, 0xa1, 0x99, 0x94, 0x30, 0xd3, 0x0e, 0xfc, 0x89, 0x56,
	0x6a, 0x29, 0x9d, 0x7a, 0x4f, 0xeb, 0x26, 0x7a, 0x17, 0x93, 0x8b, 0x31, 0xff, 0x67, 0x10, 0xd6,
	0x0f, 0xfc, 0x09, 0x6e, 0x46, 0x82, 0xc2, 0x41, 0x34, 0x94, 0x40, 0x65, 0x01, 0x44, 0x43, 0x11,
	0x24, 0x28, 0xe8, 0x35, 0xec, 0xe5, 0x12, 0x2d, 0xdc, 0xd0, 0xa4, 0x64, 0xea, 0x11, 0x9f, 0x99,
	0x33, 0x97, 0x32, 0xad, 0xc2, 0x81, 0xf7, 0xa5, 0x64, 0xe7, 0x6e, 0x68, 0x24, 0xbe, 0x63, 0x97,
	0x32, 0xbc, 0x13, 0xad, 0x2e, 0x70, 0xfc, 0x32, 0xa7, 0x84, 0xdf, 0x10, 0xf0, 0x59, 0x3a, 0x09,
	0xbf, 0xba, 0x20, 0xa4, 0x8f, 0x8f, 0x81, 0x92, 0x68, 0xe1, 0xda, 0x24, 0xc1, 0x57, 0xd7, 0xa4,
	0x37, 0x08, 0x33, 0x12, 0x9f, 0x90, 0xbe, 0x58, 0x10, 0xd2, 0x4b, 0xf8, 0xda, 0x9a, 0xf4, 0x12,
	0x7e, 0x75, 0x41, 0x48, 0xef, 0x90, 0x59, 0x11, 0xff, 0xd7, 0x9a, 0xf4, 0x03, 0x32, 0x5b, 0x9d,
	0xbe, 0x58, 0x10, 0xd2, 0x4b, 0xf8, 0xcd, 0x35, 0xe9, 0x25, 0xfc, 0xea, 0x42, 0xfb, 0x31, 0xec,
	0xac, 0x39, 0x50, 0xb4, 0x0f, 0x65, 0xba, 0xb0, 0x35, 0xa5, 0x55, 0xee, 0xd4, 0x7b, 0x7f, 0x67,
	0x5f, 0x42, 0xea, 0xc0, 0x71, 0xad, 0xbd, 0x0b, 0x3b, 0x6b, 0xce, 0xab, 0xfd, 0x24, 0x07, 0x16,
	0xb6, 0xf4, 0x20, 0x0f, 0xfe, 0x47, 0x00, 0x0f, 0x07, 0x32, 0x5a, 0xc8, 0xfc, 0xa3, 0x0c, 0x4d,
	0xf1, 0xeb, 0x42, 0xff, 0x41, 0x95, 0x32, 0x8b, 0xcd, 0xa9, 0xa6, 0xb4, 0x94, 0x8e, 0x8a, 0xd3,
	0x15, 0x3a, 0x84, 0x26, 0xb3, 0x43, 0xcb, 0x66, 0xee, 0x82, 0x30, 0xd7, 0x23, 0xc1, 0x9c, 0xf1,
	0x2f, 0x55, 0xc5, 0x92, 0x8e, 0xba, 0x80, 0x98, 0x1d, 0xba, 0x7e, 0xd1, 0x5d, 0xe6, 0xee, 0x15,
	0x15, 0x74, 0x0f, 0x60, 0xee, 0x84, 0x99, 0xaf, 0xc2, 0x7d, 0x39, 0x25, 0xee, 0x4d, 0xaf, 0x7c,
	0xdb, 0xb3, 0x28, 0x23, 0x51, 0xf2, 0x28, 0xff, 0x58, 0x54, 0x2c, 0xe9, 0xa8, 0x0d, 0x8d, 0xa5,
	0xe6, 0x3a, 0x7c, 0xea, 0x55, 0x5c, 0xd0, 0xd0, 0x01, 0xa8, 0xb9, 0xf5, 0xc4, 0xe7, 0xb3, 0xbb,
	0x89, 0x8b, 0x62, 0xd6, 0xf5, 0x8d, 0x65, 0xbf, 0x9b, 0xa7, 0x1b, 0xe4, 0x53, 0x98, 0x76, 0xcd,
	0xeb, 0x59, 0xd7, 0x44, 0x73, 0x1d, 0x3e, 0x4e, 0x69, 0xd7, 0x4c, 0xcb, 0xba, 0xa6, 0xeb, 0x89,
	0xaf, 0xc1, 0xb2, 0xeb, 0xad, 0x18, 0x9f, 0xff, 0xcc, 0x61, 0x57, 0x21, 0xd1, 0xea, 0xc9, 0xf9,
	0x27, 0x2b, 0x84, 0xa0, 0x32, 0x73, 0xdc, 0x50, 0x6b, 0xb4, 0xca, 0x1d, 0x15, 0xf3, 0xff, 0xa8,
	0x07, 0xb0, 0x70, 0xc3, 0xf4, 0x0e, 0xd1, 0x54, 0x3e, 0x07, 0x28, 0x9b, 0x83, 0xe5, 0xe5, 0x80,
	0x73, 0xae, 0xf6, 0x4b, 0x68, 0x8a, 0x17, 0x21, 0x7a, 0x08, 0xb5, 0x88, 0x30, 0xd3, 0xa3, 0x53,
	0xfe, 0xd2, 0xeb, 0xbd, 0xad, 0x0c, 0x82, 0x09, 0x1b, 0xd1, 0x29, 0xae, 0x46, 0xfc, 0x17, 0x69,
	0x50, 0x5b, 0x90, 0x88, 0xba, 0x81, 0xcf, 0xdf, 0xfd, 0x26, 0xce, 0x96, 0xed, 0xf7, 0xb9, 0x31,
	0x15, 0xae, 0xa5, 0x47, 0x50, 0xe1, 0xfb, 0x89, 0xd1, 0x5b, 0xbd, 0x7f, 0x97, 0x73, 0xca, 0x2d,
	0xa7, 0xe1, 0xf8, 0x2a, 0x24, 0x98, 0x5b, 0x84, 0x0d, 0x95, 0xee, 0xb4, 0xa1, 0x1b, 0x25, 0x37,
	0xe1, 0x42, 0xeb, 0x3b, 0x6f, 0xec, 0x0f, 0x1a, 0xdf, 0xee, 0xab, 0xfc, 0xdb, 0x7d, 0x1d, 0x7e,
	0x28, 0x41, 0xad, 0xef, 0x39, 0xb1, 0x82, 0x76, 0x61, 0x1b, 0xeb, 0x2f, 0xcc, 0xf1, 0xd1, 0xab,
	0xa7, 0x83, 0x91, 0x69, 0xe8, 0x63, 0xb3, 0x7f, 0x7a, 0xf2, 0xac, 0xf9, 0xf1, 0x5a, 0xe1, 0x25,
	0xe3, 0x4c, 0x2a, 0xdd, 0x5c, 0x2b, 0x68, 0x1f, 0xf6, 0x72, 0x4f, 0x9d, 0x0f, 0xcf, 0x4c, 0x43,
	0x3f, 0x1a, 0xe9, 0x27, 0x63, 0xf3, 0x78, 0x68, 0x8c, 0x9b, 0x9f, 0x52, 0xcb, 0xf2, 0x69, 0xc9,
	0xf2, 0x59, 0xa2, 0xc4, 0x0d, 0x0c, 0x1d, 0x9f, 0x0f, 0xfb, 0x7a, 0x62, 0xf9, 0x22, 0x51, 0x24,
	0xcb, 0x57, 0x89, 0x32, 0xd0, 0x8f, 0x8b, 0x96, 0x6f, 0x12, 0x45, 0xb2, 0x7c, 0xbf, 0x56, 0x7e,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x28, 0x89, 0xe2, 0x6c, 0x55, 0x08, 0x00, 0x00,
}
